### ISSUE TITLE
Migrate to openJ9 0.29 and remove openj9 0.27

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/jdk-index#26]
OpenJ9 0.27 has stopped receiving updates and has been superseded by OpenJ9 0.29. We should consider dropping it from the build. This is valid for both JDK8 and JDK11.

@durban I will leave the two versions co-existing for a while. Let me know when the old one can be dropped.

**Comment by vasilmkd** [comment]
Closed with #36.

**Comment by durban** [comment]
@vasilmkd Sorry for not getting back to you. Yes, I'm fine with dropping the old one.
